### ISSUE TITLE
Provide FMUs with source code

### ISSUE THREAD

**Issue by t-sommer** [Maplesoft-fmigroup/MapleSim_FMI#8]
In the old cross-check you provided FMUs with source code, e.g. https://github.com/modelica/fmi-cross-check/blob/master/fmus/2.0/cs/c-code/MapleSim/2021.2/Rectifier/Rectifier.fmu

Would it be possible to re-export the FMUs in this repository with source code as well?

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer  Hi Torsten, our current policy is not to include source code in publicly available FMUs. However, we're happy to provide you with one for personal use. Would that be acceptable?

**Comment by t-sommer** [comment]
Thanks for the offer. I'll get back to you.
